# Generated by Django 4.2.3 on 2023-07-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapstick',
            old_name='flavor',
            new_name='flavour',
        ),
    ]
