# Generated by Django 4.2.3 on 2023-07-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_flavor_chapstick_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChewMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
                ('chapstick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chapstick')),
            ],
        ),
    ]
