# Generated by Django 4.2.3 on 2023-07-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_chewmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChewMarks',
            new_name='ChewMark',
        ),
    ]
