# Generated by Django 4.2.3 on 2023-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_chewmarks_chewmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidekick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chewmark',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='chapstick',
            name='sidekicks',
            field=models.ManyToManyField(to='main_app.sidekick'),
        ),
    ]
